Close to finishing up re-doing all the scripts so they work nicely together.

diff --git a/utils/chimeraPolish b/utils/chimeraPolish
--- a/utils/chimeraPolish
+++ b/utils/chimeraPolish
@@ -1,58 +1,141 @@
 #!/bin/bash
-
-if [ $# -eq 0 ]; then echo "Usage: $( basename ${0} ) asm.fofn" ; exit ; fi
-
-export FOFN=${1}
-
-if [ -z ${FOFN} ]; then export FOFN=asm.fofn ; fi
-
-
-source ~/.bash_profile
-source ~/software/conda/source-conda-for-scripts.sh
-conda activate miniasm
-
-export READS=~/jurban/data/coral/R01-L01/combined_fastqs/all.fastq
-#export READS=~/jurban/data/coral/R01-L01/combined_fastqs/pass.fastq
+set -e
+#################################################################
+#source ~/.bash_profile
+#source ~/software/conda/source-conda-for-scripts.sh
+#conda activate miniasm
+#conda activate medaka
+#conda activate medakaOct2022
 
 
-export PATH=/central/groups/carnegie_poc/jurban/software/flye/Flye/bin:${PATH}
+## Collecting some VARs
+export SCRIPTNAME=$( basename ${0} )
+export SUBSCRIPTDIR=$( dirname ${0} )
+if [ -z ${UTILS} ]; then export UTILS=$( dirname ${0} ) ; fi	## should be same as SUBSCRIPT DIR ; if running racoonFlyFish, it will already be in ENV, else it will be taken from versions.txt
+export PATH=${UTILS}:${PATH}					## To be sure ; and especially when this script run directly.
 
-export FLYE=/central/groups/carnegie_poc/jurban/software/flye/Flye/bin/flye
-export READTYPE=--nano-hq	#--nano-raw
-#export GSIZE=400m
-export GSIZE=800m
+## Early source needs
+source ${UTILS}/versions.txt
+source ${UTILS}/helper-functions.txt
+
+
+
+## VERSION MESSAGE
+version_check ${@}
+
+
+## HELP
+if [ $# -eq 0 ]; then echo "Usage: $( basename ${0} ) asm.fofn" ; flyhelp ; exit ; fi
+
+
+
+
+
+##############################################################################
+## REQUIRED
+##############################################################################
+export FOFN=""
+export READS=""
+export MODEL=""
+
+##############################################################################
+## DEFAULTS
+##############################################################################
+export SCRIPTDIR=${SCRIPTDIR}	## Empty if using this script directly, i.e. not using racoonFlyFish
+
+export MODEL=r941_min_sup_g507
+
+export READS=""
+
+export THREADS=16
+export P=${THREADS}
+
+
+export CHIMERA_RACONROUNDS=1
+export CHIMERA_FLYEROUNDS=1
+export CHIMERA_MEDAKAROUNDS=1
 
 export RACONITERS=1
 export FLYEITERS=1
 export MEDAKAITERS=1
 
-export MODEL=r941_min_sup_g507
+
+export MAINWD=${PWD}
+export SLURM=false      ## if true, THREADS or P also used for NTASKS
+export TIME=12:00:00    ## SLURM option
+export MEM=80G          ## SLURM option
 
 
-export P=16
-export TIME=24:00:00
+export ALLVARS=""
+
 export MEM=80G
+export TIME=12:00:00
+
+export MEDAKA=$( which medaka_consensus )
+export MM2=$( which minimap2 )
+export MINMAP2=$( which minimap2 )
+export FLYE=$( which flye )
+export RACON=$( which racon )
+
+
+export DEBUG=true
+export CONTINUE=true
+export HELP=false
+export VERBOSE=false
+
+
+##############################################################################
+## GET OPTS
+##############################################################################
+while getopts "i:R:t:r:ST:M:G:d:Hv" arg; do
+    case $arg in
+        i) export FOFN=${OPTARG} ; FOFNMODE=true ;;
+        R) export READS=${OPTARG} ;;
+        r) export RACONITERS=${OPTARG} ;
+        f) export FLYEITERS=${OPTARG} ;
+        k) export MEDAKAITERS=${OPTARG} ;
+        t) export THREADS=${OPTARG} ; export P=${THREADS} ;;
+        S) export SLURM=true ;;
+        T) export TIME=${OPTARG} ;;
+        M) export MEM=${OPTARG} ;;
+        x) export X=${OPTARG} ;;
+        G) export GSIZE=${OPTARG} ;;
+        d) export READTYPE=${OPTARG} ;;
+        m) export MODEL=${OPTARG} ;;
+        v) export VERBOSE=true ;;
+        *) help; exit;;
+    esac
+done
 
 
 
 
-OUTDIR=triopol_output
-mkdir -p ${OUTDIR} && cd ${OUTDIR}
-export MAIN=${PWD}
+##############################################################################
+## PROCESSING ARGS
+##############################################################################
+if [ -z ${MM2} ]; then echo "minimap2 not found in PATH. Please add it to PATH. Exiting..." ; echo ; medakahelp ; exit ; fi
+if [ -z ${FLYE} ]; then echo "flye not found in PATH. Please add it to PATH. Exiting..." ; echo ; medakahelp ; exit ; fi
+if [ -z ${RACON} ]; then echo "racon not found in PATH. Please add it to PATH. Exiting..." ; echo ; medakahelp ; exit ; fi
+if [ -z ${MEDAKA} ]; then echo "medaka_consensus not found in PATH. Please add it to PATH. Exiting..." ; echo ; medakahelp ; exit ; fi
 
-while read line ; do
-  ARR=( $( echo $line ) )
-  B=${ARR[0]}			#raconpol
-  DIR=${B}			#flyepol/medaka
-  ASM=${ARR[1]} 		#racon/flye/medaka
-  SCRIPT=trio-polishing-on-${DIR}.sh
-  
-  ## make dir	for starting ASM to do all operations under
-  WD=${MAIN}/${DIR}
-  mkdir ${WD} && cd ${WD} 
 
-  echo ${DIR}
+for REQUIRED in FOFN READS X GSIZE READTYPE MODEL  ; do echo -e "REQUIRED\t${REQUIRED}\t${!REQUIRED}" ; if [ -z ${!REQUIRED} ]; then echo ${REQUIRED} is a required argument. Not given. Exiting. ; echo ; flyhelp ; fi ; done
+for ARG in CHIMERA_RACONROUNDS CHIMERA_FLYEROUNDS CHIMERA_MEDAKAROUNDS  THREADS SLURM TIME MEM ; do echo -e "OPTIONS\t${ARG}\t${!ARG}" ; done
 
+
+
+
+##############################################################################
+## EXECUTE
+##############################################################################
+chimera_polish_loop
+
+exit
+
+
+
+
+function write_chimera_script {
   ## INIT SCRIPT
   echo "#!/bin/bash" > ${SCRIPT}
   echo "source ~/.bash_profile" >> ${SCRIPT}
@@ -99,16 +182,37 @@ while read line ; do
     ASM=${MITERDIR}/consensus.fasta
   done
   echo -e "ln -s ${ASM} 03-raconpol-flyepol-medaka.fasta \n" >> ${SCRIPT}
+}
 
-  sbatch --time=${TIME} --nodes 1 --ntasks ${P} -J triopolish-${B} -o slurm-${B}-triopolish-%A.out --export=ALL --mem=${MEM} ${SCRIPT}
-  echo
 
-  ## Come back out of init asm DIR
-  cd ../
-done < ${FOFN}
+function chimera_polish_loop {
+  OUTDIR=triopol_output
+  mkdir -p ${OUTDIR} && cd ${OUTDIR}
+  export MAIN=${PWD}
+  
+  while read line ; do
+    export ARR=( $( echo $line ) )
+    export B=${ARR[0]}			#raconpol
+    export DIR=${B}			#flyepol/medaka
+    export ASM=${ARR[1]} 		#racon/flye/medaka
+    export SCRIPT=trio-polishing-on-${DIR}.sh
+  
+    ## make dir	for starting ASM to do all operations under
+    WD=${MAIN}/${DIR}
+    mkdir ${WD} && cd ${WD} 
+  
+    echo ${DIR}
+    write_chimera_script 
 
-wait
+    export JOBNAME=chimerapolish-${B}
+    export OUTNAME=slurm-${B}-triopolish-%A.out
+    echo
 
+    ## Come back out of init asm DIR
+    cd ../
+  done < ${FOFN}
+  wait
+}
 
 
 
diff --git a/utils/flyePolish b/utils/flyePolish
--- a/utils/flyePolish
+++ b/utils/flyePolish
@@ -1,38 +1,116 @@
 #!/bin/bash
-
-if [ $# -eq 0 ]; then echo "Usage: $( basename ${0} ) asm.fofn" ; exit ; fi
-
-export FOFN=${1}
-
-if [ -z ${FOFN} ]; then export FOFN=asm.fofn ; fi
+set -e
+#################################################################
 
 
-source ~/.bash_profile
-source ~/software/conda/source-conda-for-scripts.sh
-export PATH=/central/groups/carnegie_poc/jurban/software/flye/Flye/bin:${PATH}
+## Collecting some VARs
+export SCRIPTNAME=$( basename ${0} )
+export SUBSCRIPTDIR=$( dirname ${0} )
+if [ -z ${UTILS} ]; then export UTILS=$( dirname ${0} ) ; fi	## should be same as SUBSCRIPT DIR ; if running racoonFlyFish, it will already be in ENV, else it will be taken from versions.txt
+export PATH=${UTILS}:${PATH}					## To be sure ; and especially when this script run directly.
+
+## Early source needs
+source ${UTILS}/versions.txt
+source ${UTILS}/helper-functions.txt
+
+
+
+## VERSION MESSAGE
+version_check ${@}
+
+
+## HELP
+if [ $# -eq 0 ]; then echo "Usage: $( basename ${0} ) asm.fofn" ; flyhelp ; exit ; fi
+
+
+
+
+
+#source ~/.bash_profile
+#source ~/software/conda/source-conda-for-scripts.sh
+
+
+##############################################################################
+## REQUIRED
+##############################################################################
+export FOFN=""
+export READS=""
+export GSIZE=""
+export READTYPE=""	#nano-hq	#nano-raw
+
+##############################################################################
+## DEFAULTS
+##############################################################################
+export SCRIPTDIR=${SCRIPTDIR}	## Empty if using this script directly, i.e. not using racoonFlyFish
+
+
+export THREADS=16
+export P=${THREADS}
+
+export FLYEROUNDS=4
+export ITERS=${FLYEROUNDS}
+export ROUNDS=${FLYEROUNDS}
+
+export MAINWD=${PWD}
+export SLURM=false      ## if true, THREADS or P also used for NTASKS
+export TIME=12:00:00    ## SLURM option
+export MEM=80G          ## SLURM option
+
+export MM2=$( which minimap2 )
+export FLYE=$( which flye )
+
+export ALLVARS=""
 export P=16
 export MEM=80G
 export TIME=8:00:00
 
-export READS=~/jurban/data/coral/R01-L01/combined_fastqs/all.fastq
-######export READS=~/jurban/data/coral/R01-L01/combined_fastqs/pass.fastq
-export ITERS=4
-export FLYE=/central/groups/carnegie_poc/jurban/software/flye/Flye/bin/flye
-export READTYPE=--nano-hq	#--nano-raw
-#export GSIZE=400m
-export GSIZE=800m
+export ITERS=${FLYEROUNDS}
+export FLYE=$( which flye )
 
 
-OUTDIR=flyepol_output
-mkdir -p ${OUTDIR} && cd ${OUTDIR}
+export DEBUG=true
+export CONTINUE=true
+export HELP=false
+export VERBOSE=false
+export FLYEHELP=false
 
-while read line ; do
-  ARR=( $( echo $line ) )
-  DIR=${ARR[0]}
-  ASM=${ARR[1]}
-  SCRIPT=${DIR}.sh
-  echo ${DIR}
-  echo "#!/bin/bash" > ${SCRIPT}
-  echo "${FLYE} --genome-size ${GSIZE} ${READTYPE} ${READS} --out-dir ${DIR} --threads ${P} --polish-target ${ASM} --iterations ${ITERS}" >> ${SCRIPT}
-  sbatch --time=${TIME} --nodes 1 --ntasks ${P} -J flyepol-${DIR} -o slurm-${DIR}-flyepol-%A.out --export=ALL --mem=${MEM} ${SCRIPT}
-done < ${FOFN}
+
+##############################################################################
+## GET OPTS
+##############################################################################
+while getopts "i:R:t:r:ST:M:G:d:Hv" arg; do
+    case $arg in
+        i) export FOFN=${OPTARG} ; FOFNMODE=true ;;
+        R) export READS=${OPTARG} ;;
+        r) export ROUNDS=${OPTARG} ; export ITERS=${OPTARG} ; export FLYEROUNDS=${OPTARG} ;;
+        t) export THREADS=${OPTARG} ; export P=${THREADS} ;;
+        S) export SLURM=true ;;
+        T) export TIME=${OPTARG} ;;
+        M) export MEM=${OPTARG} ;;
+        G) export GSIZE=${OPTARG} ;;
+        d) export READTYPE="--"${OPTARG} ;;	## d for datatype
+        H) export FLYEHELP=true ;;
+        v) export VERBOSE=true ;;
+        *) help; exit;;
+    esac
+done
+
+
+
+
+##############################################################################
+## PROCESSING ARGS
+##############################################################################
+if [ -z ${FLYE} ]; then echo "Flye not found in PATH. Please add it to PATH. Exiting..." ; echo ; flyhelp ; exit ; fi
+if $FLYEHELP ; then flye --version ; flye --help ; fi
+
+for REQUIRED in FOFN READS GSIZE READTYPE ; do echo -e "REQUIRED\t${REQUIRED}\t${!REQUIRED}" ; if [ -z ${!REQUIRED} ]; then echo ${REQUIRED} is a required argument. Not given. Exiting. ; echo ; flyhelp ; fi ; done
+for ARG in ROUNDS THREADS SLURM TIME MEM ; do echo -e "OPTIONS\t${ARG}\t${!ARG}" ; done
+
+
+
+
+##############################################################################
+## EXECUTE
+##############################################################################
+flye_polish_loop
diff --git a/utils/medakaPolish b/utils/medakaPolish
--- a/utils/medakaPolish
+++ b/utils/medakaPolish
@@ -1,37 +1,119 @@
 #!/bin/bash
-
-if [ $# -eq 0 ]; then echo "Usage: $( basename ${0} ) asm.fofn" ; exit ; fi
-
-export FOFN=${1}
-
-if [ -z ${FOFN} ]; then export FOFN=asm.fofn ; fi
-
-source ~/.bash_profile
-source ~/software/conda/source-conda-for-scripts.sh
+set -e
+#################################################################
 #conda activate medaka
-conda activate medakaOct2022
+#conda activate medakaOct2022
+
+
+## Collecting some VARs
+export SCRIPTNAME=$( basename ${0} )
+export SUBSCRIPTDIR=$( dirname ${0} )
+if [ -z ${UTILS} ]; then export UTILS=$( dirname ${0} ) ; fi	## should be same as SUBSCRIPT DIR ; if running racoonFlyFish, it will already be in ENV, else it will be taken from versions.txt
+export PATH=${UTILS}:${PATH}					## To be sure ; and especially when this script run directly.
+
+## Early source needs
+source ${UTILS}/versions.txt
+source ${UTILS}/helper-functions.txt
+
+
+
+## VERSION MESSAGE
+version_check ${@}
+
+
+## HELP
+if [ $# -eq 0 ]; then echo "Usage: $( basename ${0} ) asm.fofn" ; flyhelp ; exit ; fi
+
+
+
+
+
+##############################################################################
+## REQUIRED
+##############################################################################
+export FOFN=""
+export READS=""
+export MODEL=""
+
+##############################################################################
+## DEFAULTS
+##############################################################################
+export SCRIPTDIR=${SCRIPTDIR}	## Empty if using this script directly, i.e. not using racoonFlyFish
+
 export MODEL=r941_min_sup_g507
+
+export READS=export READS=~/jurban/data/coral/R01-L01/combined_fastqs/all.fastq
+
+export THREADS=16
+export P=${THREADS}
+
+export MEDAKAROUNDS=1
+export ITERS=${MEDAKAROUNDS}
+export ROUNDS=${MEDAKAROUNDS}
+
+export MAINWD=${PWD}
+export SLURM=false      ## if true, THREADS or P also used for NTASKS
+export TIME=12:00:00    ## SLURM option
+export MEM=80G          ## SLURM option
+
+
+export ALLVARS=""
 export P=16
 export MEM=80G
 export TIME=12:00:00
 
-export READS=export READS=~/jurban/data/coral/R01-L01/combined_fastqs/all.fastq
+export ITERS=${MEDAKAROUNDS}
+export MEDAKA=$( which medaka_consensus )
+export MM2=$( which minimap2 )
+export MINMAP2=$( which minimap2 )
+
+
+export DEBUG=true
+export CONTINUE=true
+export HELP=false
+export VERBOSE=false
+export FLYEHELP=false
+
+
+##############################################################################
+## GET OPTS
+##############################################################################
+while getopts "i:R:t:r:ST:M:G:d:Hv" arg; do
+    case $arg in
+        i) export FOFN=${OPTARG} ; FOFNMODE=true ;;
+        R) export READS=${OPTARG} ;;
+        r) export ROUNDS=${OPTARG} ; export ITERS=${OPTARG} ; export FLYEROUNDS=${OPTARG} ;;
+        t) export THREADS=${OPTARG} ; export P=${THREADS} ;;
+        S) export SLURM=true ;;
+        T) export TIME=${OPTARG} ;;
+        M) export MEM=${OPTARG} ;;
+        m) export MODEL=${OPTARG} ;;
+        H) export MEDAKAHELP=true ;;
+        v) export VERBOSE=true ;;
+        *) help; exit;;
+    esac
+done
 
 
 
-OUTDIR=medakapol_output
-mkdir -p ${OUTDIR} && cd ${OUTDIR}
 
-while read line ; do
-  ARR=( $( echo $line ) )
-  DIR=${ARR[0]}
-  ASM=${ARR[1]}
-  SCRIPT=run-medaka-on-${DIR}.sh
-  echo ${DIR}
-  echo "#!/bin/bash" > ${SCRIPT}
-  echo "source ~/.bash_profile" >> ${SCRIPT}
-  #echo "conda activate medaka" >> ${SCRIPT}
-  echo "conda activate medakaOct2022" >> ${SCRIPT}
-  echo "medaka_consensus -i ${READS} -d ${ASM} -o ${DIR} -t ${P} -m ${MODEL}" >> ${SCRIPT}
-  sbatch --time=${TIME} --nodes 1 --ntasks ${P} -J medakapol-${DIR} -o slurm-${DIR}-medaka-%A.out --export=ALL --mem=${MEM} ${SCRIPT}
-done < ${FOFN}
+##############################################################################
+## PROCESSING ARGS
+##############################################################################
+if [ -z ${MEDAKA} ]; then echo "medaka_consensus not found in PATH. Please add it to PATH. Exiting..." ; echo ; medakahelp ; exit ; fi
+if [ -z ${MM2} ]; then echo "minimap2 not found in PATH. Please add it to PATH. Exiting..." ; echo ; medakahelp ; exit ; fi
+if $MEDAKAHELP ; then medaka_consensus --version ; medaka_consensus --help ; fi
+
+for REQUIRED in FOFN READS MODEL  ; do echo -e "REQUIRED\t${REQUIRED}\t${!REQUIRED}" ; if [ -z ${!REQUIRED} ]; then echo ${REQUIRED} is a required argument. Not given. Exiting. ; echo ; flyhelp ; fi ; done
+for ARG in ROUNDS THREADS SLURM TIME MEM ; do echo -e "OPTIONS\t${ARG}\t${!ARG}" ; done
+
+
+
+
+##############################################################################
+## EXECUTE
+##############################################################################
+medaka_polish_loop
+
+exit
+
diff --git a/utils/raconPolish b/utils/raconPolish
--- a/utils/raconPolish
+++ b/utils/raconPolish
@@ -1,50 +1,111 @@
 #!/bin/bash
+set -e
+#################################################################
+#source ~/.bash_profile
+#source ~/software/conda/source-conda-for-scripts.sh
+#conda activate miniasm
 
-if [ $# -eq 0 ]; then echo "Usage: $( basename ${0} ) asm.fofn" ; exit ; fi
 
-export FOFN=${1}
+## Collecting some VARs
+export SCRIPTNAME=$( basename ${0} )
+export SUBSCRIPTDIR=$( dirname ${0} )
+if [ -z ${UTILS} ]; then export UTILS=$( dirname ${0} ) ; fi	## should be same as SUBSCRIPT DIR ; if running racoonFlyFish, it will already be in ENV, else it will be taken from versions.txt
+export PATH=${UTILS}:${PATH}					## To be sure ; and especially when this script run directly.
 
-if [ -z ${FOFN} ]; then export FOFN=asm.fofn ; fi
+## Early source needs
+source ${UTILS}/versions.txt
+source ${UTILS}/helper-functions.txt
 
-source ~/.bash_profile
-source ~/software/conda/source-conda-for-scripts.sh
-conda activate miniasm
 
-export READS=~/jurban/data/coral/R01-L01/combined_fastqs/all.fastq
-####export READS=~/jurban/data/coral/R01-L01/combined_fastqs/pass.fastq
+
+## VERSION MESSAGE
+version_check ${@}
+
+
+## HELP
+if [ $# -eq 0 ]; then raconhelp ; exit ; fi
+
+
+
+
+##############################################################################
+## REQUIRED
+##############################################################################
+export FOFN=""
+export READS=""
+export X=""	#map-ont map-pb
+
+##############################################################################
+## DEFAULTS
+##############################################################################
+export SCRIPTDIR=${SCRIPTDIR}	## Empty if using this script directly, i.e. not using racoonFlyFish
+
+
+export THREADS=16
+export P=${THREADS}
+
+export RACONROUNDS=4
+export ITERS=${RACONROUNDS}
+export ROUNDS=${RACONROUNDS}
+
+export MAINWD=${PWD}
+export SLURM=false      ## if true, THREADS or P also used for NTASKS
+export TIME=12:00:00    ## SLURM option
+export MEM=80G          ## SLURM option
+
+export MM2=$( which minimap2 )
+export RACON=$( which racon )
+
+export ALLVARS=""
 export P=16
 export MEM=24G
-export TIME=12:00:00
+export TIME=8:00:00
+
+export DEBUG=true
+export CONTINUE=true
+export HELP=false
+export VERBOSE=false
+export FLYEHELP=false
 
 
-OUTDIR=raconpol_output
-mkdir -p ${OUTDIR} && cd ${OUTDIR}
+##############################################################################
+## GET OPTS
+##############################################################################
+while getopts "i:R:t:r:ST:M:G:d:Hv" arg; do
+    case $arg in
+        i) export FOFN=${OPTARG} ; FOFNMODE=true ;;
+        R) export READS=${OPTARG} ;;
+        r) export ROUNDS=${OPTARG} ; export ITERS=${OPTARG} ; export FLYEROUNDS=${OPTARG} ;;
+        t) export THREADS=${OPTARG} ; export P=${THREADS} ;;
+        S) export SLURM=true ;;
+        T) export TIME=${OPTARG} ;;
+        M) export MEM=${OPTARG} ;;
+        d) export X=${OPTARG} ;;
+        H) export RACONHELP=true ;;
+        v) export VERBOSE=true ;;
+        *) help; exit;;
+    esac
+done
 
-while read line ; do
-  ARR=( $( echo $line ) )
-  B=${ARR[0]}
-  ASM=${ARR[1]}
-  SCRIPT=racon-${B}.sh
-  echo "#!/bin/bash" > ${SCRIPT}
-  echo "source ~/.bash_profile" >> ${SCRIPT}
-  echo -e "conda activate miniasm\n" >> ${SCRIPT}
-  i=0
-  echo -e "extractFastxEntries.py --minlen 1 -f ${ASM} > racon-${B}_${i}.fasta\n" >> ${SCRIPT}
-  for j in 1 2 3 4 ; do 
-    ASM=racon-${B}_${i}.fasta
-    PAF=${B}_${j}.paf
-    OUT=racon-${B}_${j}.fasta
-    echo -e "minimap2 -t ${P} -x map-ont ${ASM} ${READS} > ${PAF}\n"  >> ${SCRIPT}
-    echo -e "racon -t ${P} ${READS} ${PAF} ${ASM} > ${OUT}\n" >> ${SCRIPT}
-    i=${j}
-  done
 
-  sbatch --time=${TIME} --nodes 1 --ntasks ${P} -J raconpol-${B} -o slurm-${B}-raconpol-%A.out --export=ALL --mem=${MEM} ${SCRIPT}
-  echo
-done < ${FOFN}
 
-wait
 
+##############################################################################
+## PROCESSING ARGS
+##############################################################################
+for REQUIRED in RACON MINIMAP2 ; do if [ -z ${REQUIRED} ]; then echo "${REQUIRED} not found in PATH. Please add it to PATH. Exiting..." ; echo ; raconhelp ; exit ; fi
+if $RACONHELP ; then racon --version ; racon --help ; fi
+
+for REQUIRED in FOFN READS X ; do echo -e "REQUIRED\t${REQUIRED}\t${!REQUIRED}" ; if [ -z ${!REQUIRED} ]; then echo ${REQUIRED} is a required argument. Not given. Exiting. ; echo ; flyhelp ; fi ; done
+for ARG in ROUNDS THREADS SLURM TIME MEM ; do echo -e "OPTIONS\t${ARG}\t${!ARG}" ; done
+
+
+
+
+##############################################################################
+## EXECUTE
+##############################################################################
+racon_polish_loop
 
 exit
 
